# Generated by Django 4.2.5 on 2023-09-21 02:52

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "userid",
                    models.AutoField(
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                        verbose_name="아이디",
                    ),
                ),
                ("userpw", models.CharField(max_length=50, verbose_name="비밀번호")),
                ("username", models.CharField(max_length=50, verbose_name="회원 이름")),
                (
                    "phone",
                    models.CharField(max_length=50, null=True, verbose_name="회원 연락처"),
                ),
            ],
        ),
    ]
